### ISSUE TITLE
Explanation of how PH knows which variables are "the same" across scenarios

### ISSUE THREAD

**Issue by junglegobs** [NREL/ProgressiveHedging.jl#27]
I recently realised that it's not clear to me how PH "knows" which stage variables are "the same" across scenarios. I assume its from the order in which they appear in the `stage1` / `stage2` vectors (see below)?

```julia
vdict = Dict{PH.StageID, Vector{JuMP.VariableRef}}([PH.stid(1) => stage1,
                                                    PH.stid(2) => stage2,
                                                    PH.stid(3) => stage3,
                                                    ])
```

Following on from that, does that mean that each scenario must have the same number of variables?

This may be trivial, but I think it's worth clarifying / keeping in mind for writing documentation.

**Comment by junglegobs** [comment]
Ah ok, that's convenient. So say scenarios 0 and 1 share a first stage variable, `x_1`, and scenarios 1 and 2 share a first stage variable `x_2` - how is the mean of `x_1` and `x_2` calculated? Say you have equal probabilities for the scenarios, is the expression something like:
```julia
x_1_hat = sum(p[s] * x_1[s] for s in scenarios if haskey(x_1, s))
```
Or do you use the probability of all scenarios, even if a first stage variable doesn't appear in that scenario? Intuitively I think what I've written above should be correct, and not the latter (see below). Or does it not make sense from a theoretical point of view to have first stage variables which don't appear in all scenarios?
```julia
x_1_hat = sum(p[s] * x_1[s] for s in scenarios)
```

**Comment by jmaack24** [comment]
Generally all first stage variables are assumed to exist in each scenario.  If they don't, mathematically, you can still add the necessary lagrangian and proximal terms to the objective function of that scenario subproblem and for that scenario, the variable will always take on the consensus value since that minimizes the proximal term and the corresponding dual variable will always be zero.

If you try this setup with PH.jl, I'm not sure what will happen.  I definitely assumed when writing the code that the variables at a given node in the scenario tree are present in all scenarios in that node's scenario bundle.  My guess is that something will break somewhere, but I'm not sure without running through everything.

The answer to your original question is the mean is computed with the _conditional_ expectation:
```julia
x_1_hat = sum(p[s] * x_1[s] for s in scenarios(x_1)) / sum(p[s] for s in scenarios(x_1))
```
where `scenarios(x_1)` denotes all the scenarios to which `x_1` belongs.  This computation is found in `algorithm.jl` in the function `compute_and_save_xhat` if you want to check it out in the code.

**Comment by junglegobs** [comment]
Thanks! So I guess it should be ok (theoretically and when using PH.jl) if the staged variables are not in every scenario.

I ask because I had an idea for including long term storage in PH, where the storage has a state of charge which is linked between scenarios (e.g. if the scenarios are the 365 days in the year). You can create additional first stage variables which represent the state of charge at the end / start of day and then hedge them such that they eventually agree with each other.

Perhaps someone already did this, but I haven't come across it. Incorporating long term storage was an issue which had been bugging me for a while, and I think this resolves it in a neat way (with optimality guarantees etc).

**Comment by jmaack24** [comment]
To clarify: I'm not actually sure what will happen in PH.jl if you have first stage models that are not present in every scenario.  It may work. It may break in some unusual way where it is not even obvious that it is broken.  When writing the code, I assumed that every variable at a scenario tree node would be present in each scenario associated with that node.  I would be **very cautious** of writing such a model for use with this software.

**Comment by junglegobs** [comment]
Noted - in any case I am testing this to see if it works (i.e. gives the same result as an equivalent extensive formulation). Made some progress, but so far no success.
