### ISSUE TITLE
Implementing scaled penalty parameter

### ISSUE THREAD

**Issue by junglegobs** [NREL/ProgressiveHedging.jl#8]
Hello! I'm using this package for a generation expansion planning problem, and I would like to extend it to have a scaled penalty parameter as [described in this Jean Paul Watson paper](http://www.optimization-online.org/DB_FILE/2008/09/2089.pdf). This should be somewhat straightforward once [getting coefficients from JuMP expressions is implemented](https://github.com/jump-dev/JuMP.jl/issues/2371) (though it's already possible now).

I'm raising this issue since I thought it makes sense to make this update available for everyone and not just do it for myself. Do any of the maintainers have any thoughts on how best to implement this? Then I can do it and then just do a pull request.

**Comment by junglegobs** [comment]
Regarding this, my idea was roughly to:

- Create a type for the penalty parameter, e.g. `PHPenalty`
- `PHPenalty` would contain a dictionary mapping first stage variables to a penalty (similarly to the different penalties for generation and transmission variables [used here](https://cfwebprod.sandia.gov/cfdocs/CompResearch/docs/CMSMunozWatson.pdf))
- `PHPenalty` would also contain a boolean to turn scaling on or off. Scaling would be done according to the paper I referenced in the previous comment (for now I would just stick to the equation on page 5 or so which specifies the scaling for continuous variables).

Scaling the penalty parameter requires the linear coefficient of the variable in the objective function. Obtaining this should be simple enough [once this pull request with JuMP is completed](https://github.com/jump-dev/JuMP.jl/pull/2442).

**Comment by jmaack24** [comment]
One of the goals of this package is to provide a PH implementation that researchers can easily modify.  So I always want to make features easy to extend. I think here what we could do is create an abstract penalty parameter type:
```
abstract type AbstractPenaltyParameter end
```
Then create a concrete type for any parameter methodology that we want to implement. So the normal scalar one would be something like
```
struct ScalarPenaltyParameter <: AbstractPenaltyParameter
    value::Float64
end
```
This would allow someone (perhaps us) to implement adaptive penalty parameters with minimal impact.

The other design methodology you need to know is that I tried to encapsulate all the interactions with the subproblem in it's own type (see the AbstractSubproblem type in the file [subproblem.jl](../blob/master/src/subproblem.jl)).  The goal here was to separate the PH implementation from whatever modeling language that the subproblem is implemented in so that if someone wants to use something other than JuMP, all they have to do is implement the AbstractSubproblem interface with the modeling language of their choice.  We want to preserve that for the scaled penalty parameter implementation.

This is a long winded way of saying that I think the concrete type for the scaled penalty would be an empty type:
```
struct ScaledPenatlyParameter <: AbstractPenaltyParameter end
```
and the necessary implementation details can be handled by the `add_ph_objective_terms` function.

I'm quite certain I have not explained this well so please ask questions on whatever you don't understand.

**Comment by junglegobs** [comment]
I think I get the idea - so you would have different methods for `add_ph_objective_terms` for the different the concrete type of the penalty parameter, in this case for `ScalarPenaltyParameter` and `ScaledPenaltyParameter`? (Or different methods for another function called by `add_ph_objective_terms`). I'll take your word on the benefits of doing it this way.

Assuming I understood your suggestion for the penalty parameter, that would mean the particular case I had in mind (penalty is scaled, and then you can assign additional weights/penalties per variable, similar to [here](https://cfwebprod.sandia.gov/cfdocs/CompResearch/docs/CMSMunozWatson.pdf), Table 2) would be possible by defining my own penalty parameter type and `add_ph_objective_terms`?

Small observation - `Scalar` and `Scaled` are very similar and I already managed to confuse the two.

**Comment by jmaack24** [comment]
Sounds like you got my idea.  The abstract typing doesn't exist yet so that will need to be implemented.  There will also be function signatures that need to be changed.  Let me know if you need any help or if you have any questions.

**Comment by jmaack24** [comment]
> Small observation - Scalar and Scaled are very similar and I already managed to confuse the two.
I agree. Feel free to rename the types.  Perhaps we could use `ProportionalPenaltyParameter` instead of `ScaledPenaltyParameter`.

**Comment by junglegobs** [comment]
So I've added the following in my fork of this repository in `subproblem.jl`:
```julia
"""
Abstract type for ProgressiveHedging penalty parameter.

Concrete sybtypes determine how this penalty is used within the PH algorithm.
"""
abstract type AbstractPenaltyParameter end

...

struct ScalarPenaltyParameter{T <: Real} 
    value::T
end
convert(::Type{T}, r::ScalarPenaltyParameter{S}) where {T<:Real, S<:Real} = T(r.value)
Base.promote_rule(::Type{ScalarPenaltyParameter{S}}, ::Type{T}) where {T<:Real, S<:Real} = T
AbstractPenaltyParameter(x::T where T <: Real) = ScalarPenaltyParameter(x)
Base.:+(x::ScalarPenaltyParameter, y::Number) = +(promote(x,y)...)
Base.:-(x::ScalarPenaltyParameter, y::Number) = -(promote(x,y)...)
Base.:*(x::ScalarPenaltyParameter, y::Number) = *(promote(x,y)...)
Base.:/(x::ScalarPenaltyParameter, y::Number) = /(promote(x,y)...)
```

If I haven't made a mistake, this means that I can change the type declarations of `r::Real` to `r::AbstractPenaltyParameter`. If r is a real number, it should be then converted to a `ScalarPenaltyParameter`. I also created some methods to make addition / subtraction etc of `ScalarPenaltyParameter` possible without writing `r.value` (though maybe this is not worth it?).

**Comment by jmaack24** [comment]
This looks like a good start.  Getting the code converted to `ScalarPenaltyParameter` is a good idea.

> this means that I can change the type declarations of r::Real to r::AbstractPenaltyParameter

I think there are a few places where I did `r::Float64` instead of `r::Real` so those will get you when you make the change.

> I also created some methods to make addition / subtraction etc of ScalarPenaltyParameter possible without writing r.value (though maybe this is not worth it?)

I wouldn't bother with the conversion stuff. The penalty parameter value is not used that many places. Also we'll need something that will work for the `ProportionalPenaltyParameter` (or whatever we decide to name it).  Probably a function call that makes use of multiple dispatch.

**Comment by jmaack24** [comment]
I was looking at the penalty parameter formulas in [Watson and Woodruff](https://link.springer.com/article/10.1007/s10287-010-0125-4) (this is the final version of the one you were looking at). I had forgotten that they use cross scenario variable values when computing the penalty term.  This means you'll have to do more than just create a new `add_ph_objective_terms` function.  I can help you with that when you get there though.

**Comment by junglegobs** [comment]
For myself there were a couple of places where a scalar penalty is assumed, e.g:
```julia
obj_s -= w_val * x_val + 1/2 * phd.r.value * (x_val - xhat_val)^2 # utils.jl, line 116, 
phd.scenario_map[s].w_vars[vid] += phd.r.value * kx # algorithm.jl, compute_and_save_w, line 138
```
Regarding the `ProportionalPenaltyParameter`, it has the same definition as `ScalarPenaltyParameter` - the value field is necessary otherwise you can't change your penalisation.

If you want I can make a pull request at this point?

**Comment by jmaack24** [comment]
> For my own reference, there were a couple of places where a scalar penalty is assumed which I haven't looked at, e.g:
>```
>obj_s -= w_val * x_val + 1/2 * phd.r.value * (x_val - xhat_val)^2 # utils.jl, line 116, 
>phd.scenario_map[s].w_vars[vid] += phd.r.value * kx # algorithm.jl, compute_and_save_w, line 138
>```

We'll need to make changes on these too so things actually work as intended.

I think a pull request is a good idea at this point so I can look at what you did a bit closer and we can figure out what to do for the above code.
